<pre>--- Summary ---
Tests passed: 0 out of 4

--- Details ---
Test #0: failed 
Test case description: ML4T-220
Traceback:
  File "grade_strategy_learner.py", line 142, in test_strategy
    in_trades_1, in_trades_2, out_trades, train_t, test_t, out_test_t = run_with_timeout(timeoutwrapper_strategylearner,max_time,(),{})
  File "grading.py", line 133, in run_with_timeout
    raise e
NameError: name 'X' is not defined

Test #1: failed 
Test case description: AAPL
Traceback:
  File "grade_strategy_learner.py", line 142, in test_strategy
    in_trades_1, in_trades_2, out_trades, train_t, test_t, out_test_t = run_with_timeout(timeoutwrapper_strategylearner,max_time,(),{})
  File "grading.py", line 133, in run_with_timeout
    raise e
NameError: name 'X' is not defined

Test #2: failed 
Test case description: SINE_FAST_NOISE
Traceback:
  File "grade_strategy_learner.py", line 142, in test_strategy
    in_trades_1, in_trades_2, out_trades, train_t, test_t, out_test_t = run_with_timeout(timeoutwrapper_strategylearner,max_time,(),{})
  File "grading.py", line 133, in run_with_timeout
    raise e
NameError: name 'X' is not defined

Test #3: failed 
Test case description: UNH - In sample
Traceback:
  File "grade_strategy_learner.py", line 142, in test_strategy
    in_trades_1, in_trades_2, out_trades, train_t, test_t, out_test_t = run_with_timeout(timeoutwrapper_strategylearner,max_time,(),{})
  File "grading.py", line 133, in run_with_timeout
    raise e
NameError: name 'X' is not defined

</pre>
